<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>ES6 语法promise的使用</title>
</head>

<style type="text/css">
    body {
        margin: 0px;
    }

    #container {
        width: 100%;
        height: 100vh;
        padding: 0px;
        background-color: #edfdef;
    }

    h1,
    h2,
    h3,
    h4,
    h5 {
        margin: 0px;
    }
</style>

<script src="../../lib/jquery/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">

</script>

<body>
    <div id="container">
        <h1>ES6 语法promise的使用Demo</h1>
        <div style="width:100%;border-style: solid;border-width: 1px;margin: 10px;">

        </div>
    </div>
</body>

<script type="text/javascript">
    // // 一个测试函数
    function readfile(fileName) {
        if (fileName === "success") {
            return "读取文件成功";
        } else {
            throw "读取文件失败";
        }
    }
    /*
        promise的第一个简单案例
    */
    console.log("-------------- 案例一 ------------------")
    const p = new Promise(function(resolve,reject){
        setTimeout(function(){
            resolve(readfile("succ"));
        },1000)
    })

    p.then(function(value){
        console.log(value)
    },function(error){
        console.error(error)
    });

    /*
        Promise.prototype.then 返回结果也是一个Promise对象，对象状态由回调函数的执行结果决定。
        1、如果回调函数返回的结果是一个非 Promise 类型的数据（不返回默认返回的是一个undifined），状态为成功
        2、是Promise 对象，则内部函数返回的promise对象状态，就是then函数返回的promise状态
        3、如果 thow 一个错误，也是一个失败的promise状态
    */
       console.log("-------------- 案例二 ------------------")
       const p2 = new Promise(function(resolve,reject){
            resolve("成功")
        })
        console.log(p2)

        var result = p2.then(value =>{
            console.log("状态1：" + value)
            // 返回一个状态为失败的Promise对象
            return new Promise((resolve,reject) => {
                reject("失败")
            })
        },reason =>{
            console.error("状态1：" + reason)
        })
        console.log(result)
        var result2 = result.then(value =>{
            console.log("状态2：" + value)
            // 返回一个非Promise对象
            return "123"
        },error =>{
            console.error("状态2：" + error)
            // 返回一个非Promise对象
            return "456"
        })
        console.log(result2)
        var result3 = result2.then(function(value){
            console.log("状态3：" + value)
            // 不返回
        },function(reasion){
            console.log("状态3：" + value)
            // 不返回
        })
        console.log(result3)
        result3.then(function(value){
            console.log("状态4：" + value)
        },function(reasion){
            console.log("状态4：" + value)
        })

    console.log("-------------- 案例三 ------------------")
    const p3 = new Promise(function (resolve, reject) {
        resolve("成功")
    })

    p3.then(function(value){
        console.log("成功1" + value)
        return new Promise(function(resove,reject){
            reject("失败")
        },function(reasion){
            console.log("失败1" + reasion)
        })
    }).then(function(value){
        console.log("成功2" + value)
    },function(reasion){
        console.log("失败2" + reasion)
    })

    /*
        Promise 对象catch方法，实际是一个语法糖，相当与then方法不传第一个参数
    */

    console.log("-------------- 案例四 ------------------")
    const p4 = new Promise(function (resolve, reject) {
        reject("出错啦")
    })

    p4.catch(function(reason){
        console.warn(reason)
    })

</script>

</html>